export interface Representante_Legal{
    nombre?: string,
    genero?: string,
    fecha_nacimiento?: string,
    entidad_nacimiento?: string,
    pais_nacimiento?: string,
    nacionalidad?: string,
    curp?: string,
    rfc?: string,
    domicilio?:string,
    estado_civil?: string,
    correo?: string,
    telefono?: number,
    documento_identificacion?: string,
}